#ifndef AFR_CORRECTION_FLAGS_H
#define AFR_CORRECTION_FLAGS_H

#define AFR_CORRECTION_CRANKING_SMTH			0x0004
#define AFR_CORRECTION_HOT_START_LEAN_LIMIT		0x0008
#define AFR_CORRECTION_NON_ZERO_LOAD			0x0010
#define AFR_CORRECTION_HIGH_COOLANT_TEMP_DISABLED	0x0080
#define AFR_CORRECTION_OVERHEAT_PROTECTION		0x0100
#define AFR_CORRECTION_POT_AFR_CONTROL			0x0400
#define AFR_CORRECTION_LEAN_SPOOL			0x0800
#define AFR_CORRECTION_KNOCK_ENRICHMENT			0x4000
#define AFR_CORRECTION_CRANKING_SMTH2			0x8000

#endif /*AFR_CORRECTION_FLAGS_H*/
