#ifndef ATCONFIG_H
#define ATCONFIG_H

#define ATCONFIG0_5TH_GEAR_ENABLED	0x02

#define ATCONFIG1_ALTERNATED_LOAD_CALC	0x01

#define ATCONFIG2_INHIBITOR_MANUAL_MODE	0x02
#define ATCONFIG2_TPS_WOT_SWITCH_CHECK	0x04

#define ATCONFIG2_TPS_IDLE_SWITCH_CHECK	0x20

#define ATCONFIG4_STOP_SWITCH_CHECK	0x01

#define ATCONFIG7_TC_LOCK_CONTROL	0x01

#define ATCONFIG10_COMBINATOR_GEAR_INDICATION	0x40

#endif /*ATCONFIG_H*/
