#ifndef MMC_IDLE_STATUS_FLAGS_H
#define MMC_IDLE_STATUS_FLAGS_H

#define IDLE_MODE_FLAGS_SAS_CORRECTION			0x0004
/*set along with reset of 0xb7*/
#define IDLE_MODE_FLAGS_LOAD_SENSOR_FAULT		0x0008

/*set at update_isv_resets, along with 0xe0 reset*/
#define IDLE_MODE_FLAGS_NOT_HA0_AT_RESET		0x0040
#define IDLE_MODE_FLAGS_HA0_AT_RESET			0x0080

#define IDLE_STATUS_FLAGS_CRANKING_OR_STALL		0x0001

#define IDLE_STATUS_FLAGS_EXTREME_RPM_DROP		0x0004
#define IDLE_STATUS_FLAGS_RPM_DIP			0x0008
#define IDLE_STATUS_FLAGS_IDLING			0x0010
#define IDLE_STATUS_FLAGS_SPARK_SPOOL			0x0020 //doesn't depend on spark spool on CS3A
#define IDLE_STATUS_FLAGS_RESET_H40			0x0040 //reset, but if set - uses constant spark spool icomp addenum

#define IDLE_STATUS2_FLAGS_SPARK_SPOOL_COOLANT_OK	0x0004

#define IDLE_STATUS2_FLAGS_ACTIVE_STEERING_3RD_PHASE	0x0010
#define IDLE_STATUS2_FLAGS_LTIC_UPDATES_ENABLED		0x0020

#define IDLE_STATUS2_FLAGS_RESET_H80			0x0080
#define IDLE_STATUS2_FLAGS_STIC_UPDATES_ENABLED		0x0100
#define IDLE_STATUS2_FLAGS_EXTREME_RPM_DROP_PREV	0x0200

#define IDLE_STATUS2_FLAGS_RESET_H4000			0x4000
#define IDLE_STATUS2_FLAGS_RESET_H8000			0x8000 //reset, but if set - regenerates icomp spark spool

#define IDLE_STATUS3_FLAGS_LOW_COOLANT_ICOMPENSATING	0x0040
#define IDLE_STATUS3_FLAGS_APPS_FAULT_IDLING		0x0080

#endif /*MMC_IDLE_STATUS_FLAGS_H*/
