#ifndef MMC_MIVEC_FLAGS_H
#define MMC_MIVEC_FLAGS_H

#define MIVEC_FLAGS_MIVEC_STUCK_PARKING		0x0001
#define MIVEC_FLAGS_SHOULD_FORCE_PARKING	0x0002
#define MIVEC_FLAGS_FORCING_PARKING_RPM		0x0004
#define MIVEC_FLAGS_FORCING_PARKING_RPM_PREV	0x0008

#define MIVEC_FLAGS_CURRENT_FEEDBACK_OK		0x0100

#define MIVEC_FLAGS_IGNITION_SWITCHED_ON	0x2000
#define MIVEC_FLAGS_IGNITION_ON_PRESTART_CHECK	0x4000
#define MIVEC_FLAGS_ACTUAL_ANGLE_AHEAD_TARGET	0x8000

#define MIVEC_CONTROLLABLE_FLAGS_NO_CONTROL	0x0001

#define MIVEC_CONTROLLABLE_FLAGS_RPM_OVER_MIN	0x0080
#define MIVEC_CONTROLLABLE_FLAGS_RPM_OVER_MAX	0x0100

#endif /*MMC_MIVEC_FLAGS_H*/
