#ifndef OPEN_CLOSED_LOOP_FLAGS_H
#define OPEN_CLOSED_LOOP_FLAGS_H

#define OPEN_LOOP_FLAGS_LOAD_TOO_HIGH_FOR_CLOSED_LOOP				0x0001
#define OPEN_LOOP_FLAGS_CONDITIONS_ALLOW_CLOSED_LOOP				0x0002
#define OPEN_LOOP_FLAGS_RICH_CONDITION_O2_REAR_ADJUSTED1			0x0004
#define OPEN_LOOP_FLAGS_H08							0x0008
#define OPEN_LOOP_FLAGS_RICH_CONDITION_CONST					0x0010
#define OPEN_LOOP_FLAGS_CLOSED_LOOP_DISABLED_DUE_TO_STOICH_CROSS_INABILITY	0x0020
#define OPEN_LOOP_FLAGS_DOWNWARD_TRIM_DIRECETION				0x0040
#define OPEN_LOOP_FLAGS_RICH_CONDITION_O2_REAR_ADJUSTED				0x0080
#define OPEN_LOOP_FLAGS_TPS_TOO_HIGH_FOR_CLOSED_LOOP				0x0100
#define OPEN_LOOP_FLAGS_LOAD_TOO_HIGH_FOR_LTFT_UPDATE				0x0200
#define OPEN_LOOP_FLAGS_H0400							0x0400
#define OPEN_LOOP_FLAGS_H0800							0x0800
//load, tps, sensor faults or coil/injector faults
#define OPEN_LOOP_FLAGS_RESTRICT_CLOSED_LOOP					0x1000
#define OPEN_LOOP_FLAGS_ONESHOT_RESET_STOICH_CROSS2_TIMER			0x2000
/*restricted closed loop operation*/
/*this one is set on engine stall only if rear o2 sensor is not enabled and reset immediately after start*/
#define OPEN_LOOP_FLAGS_CONST_STOICH_CROSS_DECAYED				0x4000
#define OPEN_LOOP_FLAGS_ONESHOT_RESET_STOICH_CROSS_TIMER_ON_ENGINE_START	0x8000

#define CLOSED_LOOP_FLAGS_FUEL_TRIM_MASK					0x000f
#define CLOSED_LOOP_FLAGS_RPM_ABOVE_IDLE					0x0010
#define CLOSED_LOOP_FLAGS_POT_AFR_CONTROL_DISABLED_DUE_TO_HIGH_LOAD		0x0020
#define CLOSED_LOOP_FLAGS_H40							0x0040
#define CLOSED_LOOP_FLAGS_LOAD_ABOVE_MIN					0x0080
#define CLOSED_LOOP_FLAGS_AIRFLOW_STABLE2					0x0100
#define CLOSED_LOOP_FLAGS_AIRFLOW_STABLE1					0x0200
#define CLOSED_LOOP_FLAGS_H400							0x0400
#define CLOSED_LOOP_FLAGS_H800							0x0800
#define CLOSED_LOOP_FLAGS_LOAD_ABOVE_ENGINE_BRAKING				0x1000
#define CLOSED_LOOP_FLAGS_HIGH_ALTERNATOR_LOAD					0x2000
#define CLOSED_LOOP_FLAGS_H4000							0x4000
#define CLOSED_LOOP_FLAGS_H8000							0x8000

#endif /*OPEN_CLOSED_LOOP_FLAGS_H*/
