#ifndef RUN_STATE_FLAGS_H
#define RUN_STATE_FLAGS_H

#define RUN_STATE_FLAGS_EXT_MASK		0x189f

#define RUN_STATE_FLAGS_CRANKING		0x0001
#define RUN_STATE_FLAGS_MAIN_LOAD_SENSOR_FAULT	0x0002
#define RUN_STATE_FLAGS_DECELERATION_FUEL_CUT	0x0004
#define RUN_STATE_FLAGS_FUEL_CUT		0x0008
#define RUN_STATE_FLAGS_STALL			0x0010
#define RUN_STATE_FLAGS_RESOLVE_TRUE_X20	0x0020

#define RUN_STATE_EXTENDED_FLAGS_OVERREV		0x0020
#define RUN_STATE_EXTENDED_FLAGS_APPS_FAULT_HALF_LIMP	0x0040

#define RUN_STATE_FLAGS_CLOSED_LOOP_GENERIC	0x0080
#define RUN_STATE_FLAGS_CAMSHAFT_FAULT_FUEL_CUT	0x0100
#define RUN_STATE_FLAGS_PROTECTIVE_FUEL_CUT	0x0200
#define RUN_STATE_FLAGS_OVERSPEED_FUEL_CUT	0x0400
#define RUN_STATE_FLAGS_CLOSED_LOOP_INBANK	0x0800

#define RUN_STATE_EXTENDED_FLAGS_STOICH_CROSS_RELATED	0x0200

#define RUN_STATE_FLAGS_TPS_SYNC_IPW_EARLY_OPERATION	0x2000

#define RUN_STATE_FLAGS_MOVING_SPARK_ASSIST	0x8000

//ext only
#define RUN_STATE_EXTENDED_FLAGS_WINTER_CRANKING		0x2000
#define RUN_STATE_EXTENDED_FLAGS_APPS_NEUTRAL_LONG		0x4000
#define RUN_STATE_EXTENDED_FLAGS_CRANKING_RELATED		0x8000

#define RUN_STATE_FLAGS_NOT_RUNNING (RUN_STATE_FLAGS_STALL | RUN_STATE_FLAGS_CRANKING)
#endif /*RUN_STATE_FLAGS_H*/
