#ifndef MMC_TORQUE_REQUEST_FLAGS_H
#define MMC_TORQUE_REQUEST_FLAGS_H

extern uint16_t torque_request_flags;

/*canrx9_data1 & 0x40*/
#define TORQUE_REQUEST_FLAGS_USE_SPARK_RETARD		0x0001
/*canrx9_data2 & 0x40*/
#define TORQUE_REQUEST_FLAGS_CAN_ASC_HIGH_LIMIT		0x0002
/*canrx9_data2 & 0x20*/
#define TORQUE_REQUEST_FLAGS_CAN_ASC_LOW_LIMIT		0x0004
#define TORQUE_REQUEST_FLAGS_VALIDATION_INCOMPLETE	0x0008
#define TORQUE_REQUEST_FLAGS_ASC_PERSISTANT_ERROR	0x0010
/*activated upon asc rx errors*/
#define TORQUE_REQUEST_FLAGS_UNKNOWN_H20		0x0020
#define TORQUE_REQUEST_FLAGS_ASC_ACTIVE_LAMP		0x0040
#define TORQUE_REQUEST_FLAGS_TORQUE_CHANGE_SLOWDOWN	0x0080
#define TORQUE_REQUEST_FLAGS_TORQUE_ERROR_POSITIVE	0x0100
#define TORQUE_REQUEST_FLAGS_ASC_ERROR_COUNTER_POSITIVE	0x0200
/*derived from canr9_data2 & 0x80*/
#define TORQUE_REQUEST_FLAGS_KEEPALIVE1			0x0400

/* depends on torque cut */
#define TORQUE_REQUEST_FLAGS_ECU_USE_SPARK_RETARD	0x1000
#define TORQUE_REQUEST_FLAGS_ASC_HIGH_LIMIT		0x2000
#define TORQUE_REQUEST_FLAGS_ASC_LOW_LIMIT		0x4000
#define TORQUE_REQUEST_FLAGS_ASC_INTERVENTION		0x8000
#endif /*MMC_TORQUE_REQUEST_FLAGS_H*/
