#ifndef MODE_SELECTOR_H
#define MODE_SELECTOR_H

#define MODE_SELECTOR_ACTIVATED			0x01
#define MODE_SELECTOR_ACTIVE			0x02
#define MODE_SELECTOR_POSITION_LIGHTS		0x04
#define MODE_SELECTOR_POSITION_LIGHTS_PREV	0x08
#define MODE_SELECTOR_ACTIVE2			0x10

#define MODE_COUNT 2

#endif /*MODE_SELECTOR_H*/
